[package]
name = "discord-bot"
version = "0.1.0"
authors = ["znemux"]
description = "Discord bot made using poise crate."
edition = "2021"

[dependencies]
poise = "0.6"
tokio = { version = "1", features = ["full"] }

[profile.release]
strip = true
opt-level = "s"
lto = true
